function html_report = html_report_model(prereport,analysis,settings)
%
% main programmer : Lin Zhe-Hui
%
    % initialize
    seperate = '<hr/>';
    html_report = {'<!DOCTYPE html>';...
                    '<html lang="zh-tw">';...
                        '<head>';...
                            '<meta charset="utf-8" />';...
                            '<link href="./html_includes/style.css" rel="stylesheet" type="text/css" />';...
                            '<script type="text/javascript" src="./html_includes/jquery-2.1.3.min.js"></script>';...
                            '<script type="text/javascript" src="./html_includes/fs.js"></script>';...
                            '<title>L&H''s ODA Analysis Report</title>';...
                        '</head>';...
                        '<body>';...
                            '<div id="fast_shift">';...
                                '<div id="mt"><b>Move to...</b></div>';...
                                '<div id="fss"><hr/>';...
                                '<hr/>';...
                                '<div id="fs_pi">Program Info</div>';...
                                '<hr/>';...
                                '<div id="fs_odi">Observation Data Info</div>';...
                                '<div id="fs_sdi">Standard Data Info</div>';...
%                                 '<div id="fs_se">Settings</div>';...
                                '<hr/>';...
                                '<div id="fs_qa">Observation Data Quality Analysis</div>';...
                                '<hr/>';...
                                '<div id="fs_sea">Standardized Data Quality Analysis</div>';...
                                '<div id="fs_su">Summary</div>'};
    if (settings.degree==6)
        html_report = [html_report;...
            '<div id="fs_d1">Polynomial Degree : 1</div>';...
            '<div id="fs_d2">Polynomial Degree : 2</div>';...
            '<div id="fs_d3">Polynomial Degree : 3</div>';...
            '<div id="fs_d4">Polynomial Degree : 4</div>';...
            '<div id="fs_d5">Polynomial Degree : 5</div>';];
    else
        html_report = [html_report;...
            '<div id="fs_d',num2str(settings.degree),'">Polynomial Degree : ',num2str(settings.degree),'</div>';];
    end
    html_report = [html_report;'</div></div>';'<h1>Observation Data Analysis Report</h1>'];
        
    % combine
    html_report = [html_report;...
                    '<h2 id="pi">';'Program Info';'</h2>'];
    for i=1:length(prereport.program_info)
        html_report = [html_report;prereport.program_info(i);'</br>'];
    end
    
    
    html_report = [html_report;...
                    seperate;...
                    
                    '<h2 id="odi">';prereport.obs.title;'</h2>';...
                    '<div id="left_side">';...
                    prereport.obs.filename;'</br>';...
                    prereport.obs.select;'</br>';...
                    prereport.obs.range;'</br>';...
                    prereport.obs.number;'</br>';...
                    '</div>';...
                    '<div id="right_side">';...
                    '<a href="./plot/observation_data.jpeg" target="_blank"><img src="./plot/observation_data.jpeg"></a>';...
                    '</div>';...
                    seperate;...
                    
                    '<h2 id="sdi">',prereport.standard.title;'</h2>';...
                    '<div id="left_side">';...
                    prereport.standard.filename;'</br>';...
                    prereport.standard.select;'</br>';...
                    prereport.standard.range;'</br>';...
                    prereport.standard.number;'</br>';...
                    '</div>';...
                    '<div id="right_side">';...
                    '<a href="./plot/standard_data.jpeg" target="_blank"><img src="./plot/standard_data.jpeg"></a>';...
                    '</div>';...
                    seperate;...
                    
%                     '<h2 id="se">',prereport.settings.title;'</h2>';...
%                     prereport.settings.degree;'</br>';...
%                     seperate;...
                    
                    '<h2 id="qa">',prereport.quality.title;'</h2>';...
                    '<div id="left_side">';...
                    prereport.quality.corr;'</br>';...
                    prereport.quality.error_range;'</br>';...
                    prereport.quality.bias;'</br>';...
                    prereport.quality.error_stdev;'</br>';...
                    prereport.quality.meanabserr;'</br>';...
                    '</div>';...
                    '<div id="right_side">';...
                    '<a href="./plot/compare.jpeg" target="_blank"><img src="./plot/compare.jpeg"></a>';...
                    '</div>';...
                    seperate;...
                    seperate;...
                    '<h2 id="sea">',prereport.regression.title;'</h2>';
                    '<h3 id="su">Summary</h3>'];
                
    if (settings.degree == 6)
        degree = 'd1';
    else
        degree = ['d',num2str(settings.degree)];
    end
    html_report = [html_report;...
                    '<table id="summary">';...
                    '<tr>';...
                    '<td>Item</td>';'<td>Correlation coefficient</td>';'<td>Error range</td>';...
                    '<td>Bias</td>';'<td>Error stdev</td>';'<td>Mean(Abs(Error))</td>';...
                    '</tr>';...
                    '<tr>';...
                    '<td>Observation</td>';...
                    '<td>',num2str(analysis.(degree).before.corr),'</td>';...
                    '<td>',num2str(analysis.(degree).before.error_range(1)),' ~ ',num2str(analysis.(degree).before.error_range(2)),'</td>';...
                    '<td>',num2str(analysis.(degree).before.bias),'</td>';...
                    '<td>',num2str(analysis.(degree).before.error_stdev),'</td>';...
                    '<td>',num2str(analysis.(degree).before.meanabserr),'</td>';...
                    '</tr>';];
    if (settings.degree == 6)
        for i=1:5
            degree = ['d',num2str(i)];
            html_report = [html_report;...
                    '<tr>';...
                    '<td>Degree ',num2str(i),'</td>';...
                    '<td>',num2str(analysis.(degree).after.corr),'</td>';...
                    '<td>',num2str(analysis.(degree).after.error_range(1)),' ~ ',num2str(analysis.(degree).after.error_range(2)),'</td>';...
                    '<td>',num2str(analysis.(degree).after.bias),'</td>';...
                    '<td>',num2str(analysis.(degree).after.error_stdev),'</td>';...
                    '<td>',num2str(analysis.(degree).after.meanabserr),'</td>';...
                    '</tr>';];
        end
    else
        degree = ['d',num2str(settings.degree)];
        html_report = [html_report;...
                    '<tr>';...
                    '<td>Degree ',num2str(settings.degree),'</td>';...
                    '<td>',num2str(analysis.(degree).after.corr),'</td>';...
                    '<td>',num2str(analysis.(degree).after.error_range(1)),' ~ ',num2str(analysis.(degree).after.error_range(2)),'</td>';...
                    '<td>',num2str(analysis.(degree).after.bias),'</td>';...
                    '<td>',num2str(analysis.(degree).after.error_stdev),'</td>';...
                    '<td>',num2str(analysis.(degree).after.meanabserr),'</td>';...
                    '</tr>';];
    end
    html_report = [html_report;'</table>'];
    if (settings.degree==6)
        for i=1:5
            degree = ['d',num2str(i)];
            html_report = [html_report;seperate;...
                            '<h3 id="',degree,'">',prereport.regression.(degree).title;'</h3>'];
            
            coe = {'Polynomial coefficient</br><table><tr>'};
            for j=1:i+1
                coe = [coe;['<td>obs<sua>',num2str(j-1),'</sua></td>']];
            end
            coe = [coe;'</tr><tr>'];
            for j=1:i+1
                coe = [coe;['<td>',num2str(prereport.regression.(degree).raw_coefficient(j)),'</td>']];
            end
            coe = [coe;'</tr></table>'];
            html_report = [html_report;coe;'</br>'];
            
            
            html_report = [html_report;'<div id="left_side">';...
                            prereport.regression.(degree).corr;'</br>';...
                            prereport.regression.(degree).error_range;'</br>';...
                            prereport.regression.(degree).bias;'</br>';...
                            prereport.regression.(degree).error_stdev;'</br>';...
                            prereport.regression.(degree).meanabserr;'</br>';'</div>'];
            html_report = [html_report;'<div id="right_side">';...
                            '<div id="even_left">';...
                            '<a href="./plot/obs_true_d',num2str(i),'_before.jpeg" target="_blank"><img src="./plot/obs_true_d',num2str(i),'_before.jpeg"></a>';...
                            '</div>';...
                            '<div id="even_right">';...
                            '<a href="./plot/obs_true_d',num2str(i),'_after.jpeg" target="_blank"><img src="./plot/obs_true_d',num2str(i),'_after.jpeg"></a>';...
                            '</div>';'</div>'];
            html_report = [html_report;'<div id="right_side">';...
                            '<div id="even_left">';...
                            '<a href="./plot/obs_err_d',num2str(i),'_before.jpeg" target="_blank"><img src="./plot/obs_err_d',num2str(i),'_before.jpeg"></a>';...
                            '</div>';...
                            '<div id="even_right">';...
                            '<a href="./plot/obs_err_d',num2str(i),'_after.jpeg" target="_blank"><img src="./plot/obs_err_d',num2str(i),'_after.jpeg"></a>';...
                            '</div>';'</div>'];
               
            
        end
    else
        degree = ['d',num2str(settings.degree)];
        html_report = [html_report;seperate;...
                            '<h3 id="',degree,'">',prereport.regression.(degree).title;'</h3>'];
        
        coe = {'Polynomial coefficient</br><table><tr>'};
        for j=1:settings.degree+1
            coe = [coe;['<td>obs<sua>',num2str(j-1),'</sua></td>']];
        end
        coe = [coe;'</tr><tr>'];
        for j=1:settings.degree+1
            coe = [coe;['<td>',num2str(prereport.regression.(degree).raw_coefficient(j)),'</td>']];
        end
        coe = [coe;'</tr></table>'];
        html_report = [html_report;coe;'</br>'];
        
        html_report = [html_report;'<div id="left_side">';...
                            prereport.regression.(degree).corr;'</br>';...
                            prereport.regression.(degree).error_range;'</br>';...
                            prereport.regression.(degree).bias;'</br>';...
                            prereport.regression.(degree).error_stdev;'</br>';...
                            prereport.regression.(degree).meanabserr;'</br>';'</div>'];
        html_report = [html_report;'<div id="right_side">';...
                            '<div id="even_left">';...
                            '<a href="./plot/obs_true_d',num2str(settings.degree),'_before.jpeg" target="_blank"><img src="./plot/obs_true_d',num2str(settings.degree),'_before.jpeg"></a>';...
                            '</div>';...
                            '<div id="even_right">';...
                            '<a href="./plot/obs_true_d',num2str(settings.degree),'_after.jpeg" target="_blank"><img src="./plot/obs_true_d',num2str(settings.degree),'_after.jpeg"></a>';...
                            '</div>';'</div>'];
        html_report = [html_report;'<div id="right_side">';...
                            '<div id="even_left">';...
                            '<a href="./plot/obs_err_d',num2str(settings.degree),'_before.jpeg" target="_blank"><img src="./plot/obs_err_d',num2str(settings.degree),'_before.jpeg"></a>';...
                            '</div>';...
                            '<div id="even_right">';...
                            '<a href="./plot/obs_err_d',num2str(settings.degree),'_after.jpeg" target="_blank"><img src="./plot/obs_err_d',num2str(settings.degree),'_after.jpeg"></a>';...
                            '</div>';'</div>'];
    end
    html_report = [html_report;'</body>';...
                    '<script>$("#fss").hide();</script>';'</html>'];
                            
    
    % output to a file
%         filename = datestr(now,'./report/yyyy-mm-dd-HH-MM');
%         filename = [filename,'.txt'];
%         fid = fopen(filename,'w+');
    [fid,errmsg] = fopen('./report/anayis_report.html','w+');
	disp(errmsg);
	lines = length(html_report);
	for i=1:lines
        fprintf(fid,'%s\r\n',html_report{i});
    end
	fclose(fid);
return