% L&H's Obs Data Analyzer
%
% main programmer : Lin Zhe-Hui
%

% initialize
clear;
version = '1.0';

% custom color
myblue =   [0.6 0.8 1.0];
myyellow = [1.0 1.0 0.6];
mygreen =  [0.6 1.0 0.6];
gray =     [0.95 0.95 0.95];

% custom parameter
handles.od.state = false;
handles.sd.state = false;

% plot user interface
f = figure('Visible','on','name','L&H''s Obs Data Analyzer',...
                        'position',[100,50,800,600],'menubar','none');

% panel : settings
handles.psettings = uipanel('Units','pixels','Title','Settings',...
                        'Position',[5,180,395,420],'BackgroundColor',myblue,'fontsize',12);
                    
    % sub panel : data
    handles.pdata = uipanel('Units','pixels','Title','Data',...
                        'Position',[10,355,385,225],'BackgroundColor',gray,'fontsize',12);
    handles.ps = uipanel('Units','pixels',...
                        'Position',[10,355,385,110],'BackgroundColor',gray,'fontsize',12);
    %
    handles.tobs = uicontrol('style','text','position',[20,470,70,90],'fontsize',12,...
                        'string','Obs','BackgroundColor',myyellow);
    handles.od.info = uicontrol('style','text','position',[90,470,295,25],'fontsize',12,...
                        'string','(obs data info)','BackgroundColor',[1 1 1]);
    handles.od.style = uicontrol('style','popupmenu','position',[160,510,75,20],'fontsize',12,...
                        'string','colume|row');
    handles.od.line = uicontrol('style','edit','position',[240,500,60,30],'fontsize',12,...
                        'string','','BackgroundColor',[1 1 1]);
    handles.od.name = uicontrol('style','text','position',[90,535,215,25],'fontsize',12,...
                        'string','(obs data file name)','BackgroundColor',[1 1 1]);
    handles.odselect = uicontrol('style','pushbutton','position',[305,535,80,25],'fontsize',12,...
                        'string','select file','BackgroundColor',myyellow);
    handles.odread = uicontrol('style','pushbutton','position',[305,500,80,30],'fontsize',12,...
                        'string','read data','BackgroundColor',myyellow);
    %
    handles.tstandard = uicontrol('style','text','position',[20,365,70,90],'fontsize',12,...
                        'string','Standard','BackgroundColor',myyellow);
    handles.sd.info = uicontrol('style','text','position',[90,365,295,25],'fontsize',12,...
                        'string','(standard data info)','BackgroundColor',[1 1 1]);
    handles.sd.style = uicontrol('style','popupmenu','position',[160,405,75,20],'fontsize',12,...
                        'string','colume|row');
    handles.sd.line = uicontrol('style','edit','position',[240,395,60,30],'fontsize',12,...
                        'string','','BackgroundColor',[1 1 1]);
    handles.sd.name = uicontrol('style','text','position',[90,430,215,25],'fontsize',12,...
                        'string','(standard data file name)','BackgroundColor',[1 1 1]);
    handles.sdselect = uicontrol('style','pushbutton','position',[305,430,80,25],'fontsize',12,...
                        'string','select file','BackgroundColor',myyellow);
    handles.sdread = uicontrol('style','pushbutton','position',[305,395,80,30],'fontsize',12,...
                        'string','read data','BackgroundColor',myyellow);
                    
    % sub panel : power
    handles.pdegree = uipanel('Units','pixels','Title','Degree',...
                        'Position',[10,285,385,65],'BackgroundColor',gray,'fontsize',12);
    handles.tdegree = uicontrol('style','text','Position',[20,300,150,20],...
                        'string','Degree of polynomial','fontsize',12,...
                        'HorizontalAlignment','left');
    handles.degree = uicontrol('style','popupmenu','Position',[175,305,70,20],...
                        'string','1|2|3|4|5|1~5','fontsize',12);
    
                    
    % sub panel : output
    handles.poutput = uipanel('Units','pixels','Title','Output',...
                        'Position',[10,185,385,95],'BackgroundColor',gray,'fontsize',12);
    handles.output_text = uicontrol('style','checkbox',...
                        'string','Generate txt report (without graphic)',...
                        'Position',[20,235,350,20],'BackgroundColor',gray,'fontsize',12);
    handles.output_plot = uicontrol('style','checkbox',...
                        'string','Output graphic',...
                        'Position',[20,215,350,20],'BackgroundColor',gray,'fontsize',12);
    handles.output_html = uicontrol('style','checkbox',...
                        'string','Generate HTML report (with graphic)',...
                        'Position',[20,195,350,20],'BackgroundColor',gray,'fontsize',12);

% bottun : analyze
handles.analyze = uicontrol('style','pushbutton','string','Analyze'...
                        ,'position',[5,135,395,35],'BackgroundColor',mygreen,'fontsize',14);

% panel : info
handles.pinfo = uipanel('Units','pixels','Title','Info',...
                        'Position',[5,5,395,120],'BackgroundColor',gray,'fontsize',12);
handles.info = uicontrol('style','text','position',[15,15,375,85],'max',5,...
                        'fontsize',12,...
                        'string',{'L&H''s Obs Data Analyzer';
                                ['Version : ',version];
                                'Author : Lin Zhe-Hui & Hsieh, C. Y.';
                                'this project is released under GPLv3'});

% panel : preview
handles.ppreview = uipanel('Units','pixels','Title','Preview',...
                        'Position',[405,290,390,310],'BackgroundColor',gray,'fontsize',12);
handles.preview = axes('Units','pixels','Position',[455,330,325,240]);

% panel : log
handles.plog = uipanel('Units','pixels','Title','Log',...
                        'Position',[405,5,390,280],'BackgroundColor',gray,'fontsize',12);
handles.log = uicontrol('style','edit','position',[410,10,380,252],...
                        'string','','BackgroundColor',[1 1 1],'fontsize',10,'max',1000,...
                        'HorizontalAlignment','left');
                    
                    
% callbacks
set(handles.odselect,'callback','handles=controller(''odselect'',handles);');
set(handles.sdselect,'callback','handles=controller(''sdselect'',handles);');
set(handles.odread,'callback','handles=controller(''odread'',handles);');
set(handles.sdread,'callback','handles=controller(''sdread'',handles);');
set(handles.output_plot,'callback','handles=controller(''output_plot'',handles);');
set(handles.output_html,'callback','handles=controller(''output_html'',handles);');
set(handles.analyze,'callback','handles=controller(''analyze'',handles);');